Traceback (most recent call last):
  File "/home/tzeng/repos/kv_na/train.py", line 264, in <module>
    losses = estimate_loss()
  File "/home/tzeng/anaconda3/envs/lm-arch-comparison/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
  File "/home/tzeng/repos/kv_na/train.py", line 224, in estimate_loss
    logits, loss = model(X, Y)
  File "/home/tzeng/anaconda3/envs/lm-arch-comparison/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 375, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/tzeng/anaconda3/envs/lm-arch-comparison/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tzeng/anaconda3/envs/lm-arch-comparison/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tzeng/anaconda3/envs/lm-arch-comparison/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 736, in compile_wrapper
    return fn(*args, **kwargs)
  File "/home/tzeng/anaconda3/envs/lm-arch-comparison/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tzeng/anaconda3/envs/lm-arch-comparison/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tzeng/repos/kv_na/model.py", line 223, in forward
    x = block(x)
  File "/home/tzeng/anaconda3/envs/lm-arch-comparison/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tzeng/anaconda3/envs/lm-arch-comparison/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tzeng/repos/kv_na/model.py", line 146, in forward
    x = x + self.attn(self.ln_1(x))
  File "/home/tzeng/anaconda3/envs/lm-arch-comparison/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tzeng/anaconda3/envs/lm-arch-comparison/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tzeng/repos/kv_na/model.py", line 81, in forward
    b, t = idx.size()
ValueError: too many values to unpack (expected 2)
